/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerVerificationStatusRouteImport } from './routes/seller/verification-status'
import { Route as SellerRegisterRouteImport } from './routes/seller/register'
import { Route as SellerOnboardingRouteImport } from './routes/seller/onboarding'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/_admin/dashboard'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/admin/_admin/users/index'
import { Route as AdminAdminTransactionsIndexRouteImport } from './routes/admin/_admin/transactions/index'
import { Route as AdminAdminSellersIndexRouteImport } from './routes/admin/_admin/sellers/index'
import { Route as AdminAdminListingsIndexRouteImport } from './routes/admin/_admin/listings/index'
import { Route as AdminAdminDocumentsIndexRouteImport } from './routes/admin/_admin/documents/index'
import { Route as AdminAdminBookingsIndexRouteImport } from './routes/admin/_admin/bookings/index'
import { Route as AdminAdminAuditLogsIndexRouteImport } from './routes/admin/_admin/audit-logs/index'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/admin/_admin/users/$userId'
import { Route as AdminAdminSellersVerificationQueueRouteImport } from './routes/admin/_admin/sellers/verification-queue'
import { Route as AdminAdminSellersSellerIdRouteImport } from './routes/admin/_admin/sellers/$sellerId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerVerificationStatusRoute =
  SellerVerificationStatusRouteImport.update({
    id: '/seller/verification-status',
    path: '/seller/verification-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/seller/register',
  path: '/seller/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/seller/onboarding',
  path: '/seller/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTransactionsIndexRoute =
  AdminAdminTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSellersIndexRoute = AdminAdminSellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminListingsIndexRoute = AdminAdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDocumentsIndexRoute =
  AdminAdminDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminBookingsIndexRoute = AdminAdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditLogsIndexRoute =
  AdminAdminAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSellersVerificationQueueRoute =
  AdminAdminSellersVerificationQueueRouteImport.update({
    id: '/sellers/verification-queue',
    path: '/sellers/verification-queue',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSellersSellerIdRoute =
  AdminAdminSellersSellerIdRouteImport.update({
    id: '/sellers/$sellerId',
    path: '/sellers/$sellerId',
    getParentRoute: () => AdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/sellers/verification-queue': typeof AdminAdminSellersVerificationQueueRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/audit-logs/': typeof AdminAdminAuditLogsIndexRoute
  '/admin/bookings/': typeof AdminAdminBookingsIndexRoute
  '/admin/documents/': typeof AdminAdminDocumentsIndexRoute
  '/admin/listings/': typeof AdminAdminListingsIndexRoute
  '/admin/sellers/': typeof AdminAdminSellersIndexRoute
  '/admin/transactions/': typeof AdminAdminTransactionsIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/sellers/verification-queue': typeof AdminAdminSellersVerificationQueueRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsIndexRoute
  '/admin/bookings': typeof AdminAdminBookingsIndexRoute
  '/admin/documents': typeof AdminAdminDocumentsIndexRoute
  '/admin/listings': typeof AdminAdminListingsIndexRoute
  '/admin/sellers': typeof AdminAdminSellersIndexRoute
  '/admin/transactions': typeof AdminAdminTransactionsIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/register': typeof SellerRegisterRoute
  '/seller/verification-status': typeof SellerVerificationStatusRoute
  '/admin/_admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/_admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/_admin/sellers/verification-queue': typeof AdminAdminSellersVerificationQueueRoute
  '/admin/_admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/_admin/audit-logs/': typeof AdminAdminAuditLogsIndexRoute
  '/admin/_admin/bookings/': typeof AdminAdminBookingsIndexRoute
  '/admin/_admin/documents/': typeof AdminAdminDocumentsIndexRoute
  '/admin/_admin/listings/': typeof AdminAdminListingsIndexRoute
  '/admin/_admin/sellers/': typeof AdminAdminSellersIndexRoute
  '/admin/_admin/transactions/': typeof AdminAdminTransactionsIndexRoute
  '/admin/_admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin'
    | '/seller/onboarding'
    | '/seller/register'
    | '/seller/verification-status'
    | '/admin/dashboard'
    | '/admin/sellers/$sellerId'
    | '/admin/sellers/verification-queue'
    | '/admin/users/$userId'
    | '/admin/audit-logs/'
    | '/admin/bookings/'
    | '/admin/documents/'
    | '/admin/listings/'
    | '/admin/sellers/'
    | '/admin/transactions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin'
    | '/seller/onboarding'
    | '/seller/register'
    | '/seller/verification-status'
    | '/admin/dashboard'
    | '/admin/sellers/$sellerId'
    | '/admin/sellers/verification-queue'
    | '/admin/users/$userId'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/documents'
    | '/admin/listings'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/admin/_admin'
    | '/seller/onboarding'
    | '/seller/register'
    | '/seller/verification-status'
    | '/admin/_admin/dashboard'
    | '/admin/_admin/sellers/$sellerId'
    | '/admin/_admin/sellers/verification-queue'
    | '/admin/_admin/users/$userId'
    | '/admin/_admin/audit-logs/'
    | '/admin/_admin/bookings/'
    | '/admin/_admin/documents/'
    | '/admin/_admin/listings/'
    | '/admin/_admin/sellers/'
    | '/admin/_admin/transactions/'
    | '/admin/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerRegisterRoute: typeof SellerRegisterRoute
  SellerVerificationStatusRoute: typeof SellerVerificationStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/verification-status': {
      id: '/seller/verification-status'
      path: '/seller/verification-status'
      fullPath: '/seller/verification-status'
      preLoaderRoute: typeof SellerVerificationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/seller/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/seller/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/dashboard': {
      id: '/admin/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/': {
      id: '/admin/_admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/transactions/': {
      id: '/admin/_admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminAdminTransactionsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/sellers/': {
      id: '/admin/_admin/sellers/'
      path: '/sellers'
      fullPath: '/admin/sellers/'
      preLoaderRoute: typeof AdminAdminSellersIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/listings/': {
      id: '/admin/_admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminAdminListingsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/documents/': {
      id: '/admin/_admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminAdminDocumentsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/bookings/': {
      id: '/admin/_admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminAdminBookingsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/audit-logs/': {
      id: '/admin/_admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AdminAdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users/$userId': {
      id: '/admin/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/sellers/verification-queue': {
      id: '/admin/_admin/sellers/verification-queue'
      path: '/sellers/verification-queue'
      fullPath: '/admin/sellers/verification-queue'
      preLoaderRoute: typeof AdminAdminSellersVerificationQueueRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/sellers/$sellerId': {
      id: '/admin/_admin/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/admin/sellers/$sellerId'
      preLoaderRoute: typeof AdminAdminSellersSellerIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminSellersSellerIdRoute: typeof AdminAdminSellersSellerIdRoute
  AdminAdminSellersVerificationQueueRoute: typeof AdminAdminSellersVerificationQueueRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminAuditLogsIndexRoute: typeof AdminAdminAuditLogsIndexRoute
  AdminAdminBookingsIndexRoute: typeof AdminAdminBookingsIndexRoute
  AdminAdminDocumentsIndexRoute: typeof AdminAdminDocumentsIndexRoute
  AdminAdminListingsIndexRoute: typeof AdminAdminListingsIndexRoute
  AdminAdminSellersIndexRoute: typeof AdminAdminSellersIndexRoute
  AdminAdminTransactionsIndexRoute: typeof AdminAdminTransactionsIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminSellersSellerIdRoute: AdminAdminSellersSellerIdRoute,
  AdminAdminSellersVerificationQueueRoute:
    AdminAdminSellersVerificationQueueRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminAuditLogsIndexRoute: AdminAdminAuditLogsIndexRoute,
  AdminAdminBookingsIndexRoute: AdminAdminBookingsIndexRoute,
  AdminAdminDocumentsIndexRoute: AdminAdminDocumentsIndexRoute,
  AdminAdminListingsIndexRoute: AdminAdminListingsIndexRoute,
  AdminAdminSellersIndexRoute: AdminAdminSellersIndexRoute,
  AdminAdminTransactionsIndexRoute: AdminAdminTransactionsIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerRegisterRoute: SellerRegisterRoute,
  SellerVerificationStatusRoute: SellerVerificationStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
